### PR TITLE
Update runtime to 22.08

### LINKED ISSUE #2: 20.08 Runtime is deprecated
Updating with `flatpak update` gives the following warning:

```
Info: runtime org.freedesktop.Platform branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   net.sourceforge.pdfchain

Info: runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   net.sourceforge.pdfchain
```

21.08 and 22.08 are both available at the time of writing.

### PR DESCRIPTION
**Pull request by hfiguiere**
- use jdk17
- update pangomm as it FTBS
- simplify manifest

Closes #2

### CODE REVIEW

**Comment by hfiguiere** [comment]
xdg-cache = bad.

removed.

**Comment by nbenitez** [comment]
Thanks for the MR, just a small regression: the PDFChain logo image is not shown in the "About" window, the console prints some messages about it:
`Icon file doesn't exist! /usr/share/pixmaps/pdfchain.png , /usr/local/share/pixmaps/pdfchain.png`

so you either don't remove this line:
`"sed -i 's,/usr/share/pixmaps/pdfchain.png,/app/share/pixmaps/net.sourceforge.pdfchain.png,g' src/constant.h",`

or leave another copy of the icon as `/app/share/pixmaps/pdfchain.png`

**Comment by hfiguiere** [comment]
I already have a fix for that.

**Comment by hfiguiere** [comment]
> so you either don't remove this line: `"sed -i 's,/usr/share/pixmaps/pdfchain.png,/app/share/pixmaps/net.sourceforge.pdfchain.png,g' src/constant.h",`
> 
> or leave another copy of the icon as `/app/share/pixmaps/pdfchain.png`

It will never find this one. the problem is the developers ignored the prefix here. see the patch I added.  (Patches are better, because they will NOT silently fail and are definitely less obscure than sed)

**Comment by hfiguiere** [comment]
And yes I tested it which is why I added the patch.

**Comment by nbenitez** [comment]
Thanks I tested your fix is good.

**Pull request merged**
